name: Lint and Test

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev']

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      server: ${{ steps.changes.outputs.server }}
      client: ${{ steps.changes.outputs.client }}
      integrations: ${{ steps.changes.outputs.integrations }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            server:
              - 'server/**'
            client:
              - 'client/**'
            integrations:
              - 'integrations/**'

  check-swagger:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: assert RTK updated with swagger
        run: |
          yarn workspace shared generate:api
          git diff --quiet

  lint-mobile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run ESLint
        run: yarn lint

      - name: Run jest tests
        run: yarn jest

      - name: Run TypeScript compilation check
        run: yarn typecheck

  lint-web:
    needs: changes
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout code
        if: ${{ needs.changes.outputs.client == 'true' }}
        uses: actions/checkout@v3

      - name: Set up Node.js
        if: ${{ needs.changes.outputs.client == 'true' }}
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'yarn'
          cache-dependency-path: 'client/yarn.lock'

      - name: Install dependencies
        if: ${{ needs.changes.outputs.client == 'true' }}
        run: |
          yarn install --frozen-lockfile
          yarn workspace web install
          git diff --exit-code yarn.lock

      - name: Install playwright
        if: ${{ needs.changes.outputs.client == 'true' }}
        run: yarn playwright install

      - name: Run ESLint
        if: ${{ needs.changes.outputs.client == 'true' }}
        run: yarn workspace web lint

      - name: Run TypeScript compilation check
        if: ${{ needs.changes.outputs.client == 'true' }}
        run: yarn workspace web typecheck

      - name: Build React app
        if: ${{ needs.changes.outputs.client == 'true' }}
        run: yarn workspace web build

      - name: Run jest tests
        if: ${{ needs.changes.outputs.client == 'true' }}
        run: yarn workspace web test

      - name: Run storybook build
        if: ${{ needs.changes.outputs.client == 'true' }}
        run: yarn workspace web build-storybook

  lint-server:
    needs: changes
    name: lint-server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout Code
        if: ${{ needs.changes.outputs.server == 'true' }}
        uses: actions/checkout@v4

      - name: Set Up Go
        if: ${{ needs.changes.outputs.server == 'true' }}
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache-dependency-path: |
            server/go.sum

      - name: Install Dependencies
        if: ${{ needs.changes.outputs.server == 'true' }}
        run: |
          go mod tidy
          go mod download

      - name: assert dev committed `go get && go mod tidy`
        if: ${{ needs.changes.outputs.server == 'true' }}
        run: |
          git diff --quiet ./go.mod ./go.sum

      - name: assert no time.Now calls
        if: ${{ needs.changes.outputs.server == 'true' }}
        run: |
          ! grep --quiet --fixed-strings --recursive --exclude-dir=clock 'time.Now' *.go pkg/ integration-tests/

      - name: assert templates generate and are formatted
        if: ${{ needs.changes.outputs.server == 'true' }}
        run: |
          go install github.com/a-h/templ/cmd/templ@v0.3.906
          templ generate
          templ fmt -fail ./templates

      - name: assert swagger is up to date
        if: ${{ needs.changes.outputs.server == 'true' }}
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          ./generate_swagger.sh
          git diff --quiet ./pkg/docs/docs.go ./pkg/docs/swagger.json ./pkg/docs/swagger.yaml

      - name: golangci-lint
        if: ${{ needs.changes.outputs.server == 'true' }}
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.2.1
          args: --timeout=5m
          working-directory: ./server

      - name: Run Unit Tests
        if: ${{ needs.changes.outputs.server == 'true' }}
        run: |
          go test ./pkg/...
          go test *.go

      - name: Login to Docker Registry for caching
        if: ${{ needs.changes.outputs.server == 'true' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        if: ${{ needs.changes.outputs.server == 'true' }}
        uses: docker/setup-buildx-action@v3

      - name: Build docker compose
        if: ${{ needs.changes.outputs.server == 'true' }}
        run: |
          echo "" > .env
          docker buildx bake --file docker-compose.yml --file docker-compose-cache.json

      - name: Run Integration Tests
        if: ${{ needs.changes.outputs.server == 'true' }}
        run: |
          echo "" > .env
          docker compose up --build --detach --wait postgresql-test sendgrid twilio debtwise plaid sardine
          go test ./integration-tests

  build-server:
    needs: [changes, lint-server]
    uses: ./.github/workflows/server-push-ecr-image.yml
    if: ${{ needs.changes.outputs.server == 'true' && github.ref == 'refs/heads/dev' }}
    with:
      rev: 'rev-${{ github.run_number }}'
      sha: ${{ github.sha }}
    secrets: inherit

  deploy-sandbox-frontend:
    needs: [changes, lint-web]
    uses: ./.github/workflows/frontend-deploy-s3.yml
    if: ${{ needs.changes.outputs.client == 'true' && github.ref == 'refs/heads/dev' }}
    with:
      environment: sandbox
      version: 'v${{ github.run_number }}'
    secrets: inherit

  deploy-production-frontend:
    needs: [changes, deploy-sandbox-frontend]
    uses: ./.github/workflows/frontend-deploy-s3.yml
    if: ${{ needs.changes.outputs.client == 'true' && github.ref == 'refs/heads/dev' }}
    with:
      environment: production
      version: 'v${{ github.run_number }}'
    secrets: inherit

  deploy-integrations:
    needs: [changes]
    uses: ./.github/workflows/integrations-deploy-s3.yml
    if: ${{ needs.changes.outputs.integrations == 'true' && github.ref == 'refs/heads/dev' }}
    with:
      environment: sandbox
      version: 'v${{ github.run_number }}'
    secrets: inherit

  deploy-production-integrations:
    needs: [changes, deploy-integrations]
    uses: ./.github/workflows/integrations-deploy-s3.yml
    if: ${{ needs.changes.outputs.integrations == 'true' && github.ref == 'refs/heads/dev' }}
    with:
      environment: production
      version: 'v${{ github.run_number }}'
    secrets: inherit
